export const HIDELOADING='HIDELOADING';
export const SHOWLOADING='SHOWLOADING';
export const LOGIN='LOGIN';
export const LOGOUT='LOGOUT';
export const REGIST='REGIST';
export const HIDESWIPERBTN='HIDESWIPERBTN';
export const SHOWSWIPERBTN='SHOWSWIPERBTN';
